### PR TITLE
pull request as requested cpt

### PR DESCRIPTION
**Pull request by AWilliams17**
i think i did that right

### CODE REVIEW

**Comment by petercunha** [comment]
You don't need to add a Fore.RESET on an exit() call

**Comment by AWilliams17** [comment]
I was having a weird problem where after the script did an exit(), the font color in my terminal emulator remained the same color the script set. Maybe it's just a weird thing on my end. My terminal is kinda odd sometimes.

**Comment by petercunha** [comment]
What terminal are you using?

I just tested it on both my Mac and Ubuntu, neither have this problem. But feel free to fix this again and open a pull request. I will merge it if it's an issue for other people.
er have this problem. But feel free to fix this again and open a pull request. I will merge it if it's an issue for other people.

**Comment by AWilliams17** [comment]
I'm using Terminator on Void Linux. I think I just may have something weird in my configuration file for it that caused it though.

**Pull request closed without merging**
